# Generated by Django 5.2.1 on 2025-05-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_thing',
            field=models.CharField(default='T-shirt', max_length=255),
        ),
    ]
