# Generated by Django 5.2.1 on 2025-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders_ordered_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager')], default='manager', max_length=100),
        ),
    ]
