name: CRM_System_Deploy

on:
  push:
    branches: [ main, master ]
  workflow_run:
    workflows: ["CRM_System"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: bek85.me
        username: root
        key: ${{ secrets.KEY }}

        script: |
          cd CRM_system/
          git pull
          systemctl restart gunicorn.service