name: CRM_System_Deploy

on:
  push:
    branches: [ main, master ]
  workflow_run:
    workflows: ["CRM_System"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: bek85.me
        username: root
        key: ${{ secrets.KEY }}
        script: |
          cd CRM_system/
          git reset --hard HEAD
          git clean -fd -e .venv
          git pull
          source .venv/bin/activate || { python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt && pip install gunicorn; }
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart gunicorn.service