name: CRM_System

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check Django setup
      run: |
        python manage.py check

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput

    - name: Show project info
      run: |
        echo "✅ Django project checked successfully"
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"







#name: CRM_System
#
#on: [push]
#
#jobs:
#  run-tests:
#    runs-on: ubuntu-latest
#    env:
#      DJANGO_SETTINGS_MODULE: clothes.settings
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-python@v2
#        with:
#          python-version: '3.x'
#      - name: Install Requirements
#      - run: pip install -r requirements.txt
#      - name: Run Tests
#      - run: pytests
